### ISSUE TITLE
DNS update fails with error: AttributeError: 'AuthorizedSession' object has no attribute 'configure_mtls_channel'

### ISSUE THREAD

**Issue by budney** [ianbrown78/google-dns-updater#3]
Hi!

I've been working through your tutorial for setting this script up, and I've hit a bit of a wall with the above-mentioned error message. It occurs during the iteration "for record in records"... Some googling suggests that the Google-cloud-core API has a bug or is unstable at the moment. Have you encountered this, and do you have a fix? Thanks!

Here's the backtrace from the GCP logs:

Traceback (most recent call last):
File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function
      result = _function_handler.invoke_user_function(flask.request)
File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function
      return call_user_function(request_or_event)
File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function
      return self._user_function(request_or_event)
File "/user_code/main.py", line 60, in main
      for record in records:
File "/env/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 214, in _items_iter
      for page in self._page_iter(increment=False):
File "/env/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 253, in _page_iter
      page = self._next_page()
File "/env/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 382, in _next_page
      response = self._get_next_page_response()
File "/env/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 442, in _get_next_page_response
      method=self._HTTP_METHOD, path=self.path, query_params=params
File "/env/local/lib/python3.7/site-packages/google/cloud/_http.py", line 480, in api_request
      timeout=timeout,
File "/env/local/lib/python3.7/site-packages/google/cloud/_http.py", line 338, in _make_request
      method, url, headers, data, target_object, timeout=timeout
File "/env/local/lib/python3.7/site-packages/google/cloud/_http.py", line 375, in _do_request
      return self.http.request(
File "/env/local/lib/python3.7/site-packages/google/cloud/_http.py", line 156, in http
      return self._client._http
File "/env/local/lib/python3.7/site-packages/google/cloud/client.py", line 214, in _http
      self._http_internal.configure_mtls_channel(self._client_cert_source)
      AttributeError: 'AuthorizedSession' object has no attribute 'configure_mtls_channel'

**Comment by ianbrown78** [comment]
Thanks for the issue report @budney.
I am looking into this now.

**Comment by ianbrown78** [comment]
HI @budney,
I have pushed a few changes to the code to bring it up to date. (Python 3.9 and various requirements updated).
The tutorial is also updated. (Service account permissions, runtime
I cannot reproduce the error in either Asia East2 or Australia Southeast 1 regions.
Give the update a try and let me know how you get on.
Thanks,
Ian

**Comment by budney** [comment]
That worked! All good now. Thanks!

I also made a shell script that checks my current IP and does a DNS lookup, to avoid calling cloud functions unnecessarily (I can't tell, but it looks like at some point Google starts charging me...). It's in my fork of your repo, in the ./bin directory.

https://github.com/budney/google-dynamic-dns

Thanks again!

**Comment by budney** [comment]
* It's actually in contrib/bin now. I also added a file that can be put in /etc/cron.d for Linux distros that support that.
